const mongoose    = require('mongoose');

let storefrontThemeSchema = mongoose.Schema({
    marketplace     : { type: mongoose.Schema.Types.ObjectId, default: null, ref: 'back_marketplace' },
    name            : { type: String                        , default: null },
    handle          : { type: String                        , default: null },
    colors_schema   : { type: {
        primary_color               : { type: String, default: null }, 
        secondary_color             : { type: String, default: null }, 
        primary_font_color          : { type: String, default: null }, 
        econdary_font_color         : { type: String, default: null }, 
        dark_font_color             : { type: String, default: null }, 
        gray_font_color             : { type: String, default: null }, 
        gray_dark_font_color        : { type: String, default: null }, 
        placeholder_color           : { type: String, default: null }, 
        btn_disabled_color          : { type: String, default: null }, 
        form_control_disabled_color : { type: String, default: null }, 
        form_control_border_color   : { type: String, default: null }, 
        primary_border_color        : { type: String, default: null }, 
        secondary_border_color      : { type: String, default: null }, 
        dark_border_color           : { type: String, default: null }, 
        gray_border_color           : { type: String, default: null }, 
        gray_dark_border_color      : { type: String, default: null }, 
        primary_svg_color           : { type: String, default: null }, 
        secondary_svg_color         : { type: String, default: null }, 
        tertiary_svg_color          : { type: String, default: null }, 
        starts_color                : { type: String, default: null }, 
        sale_tag_color              : { type: String, default: null }, 
        new_tag_color               : { type: String, default: null }, 
        primary_shadow_color        : { type: String, default: null }, 
        secondary_shadow_color      : { type: String, default: null }, 
        background_white_color      : { type: String, default: null }, 
        background_black_color      : { type: String, default: null }, 
        background_gray_color       : { type: String, default: null }
    }, default: {
        primary_color               : { type: String, default: "#303030" }, 
        secondary_color             : { type: String, default: "#FFA072" }, 
        primary_font_color          : { type: String, default: "#797979" }, 
        econdary_font_color         : { type: String, default: "#FFFFFF" }, 
        dark_font_color             : { type: String, default: "#000000" }, 
        gray_font_color             : { type: String, default: "#605755" }, 
        gray_dark_font_color        : { type: String, default: "#777777" }, 
        placeholder_color           : { type: String, default: "#000000" }, 
        btn_disabled_color          : { type: String, default: "#797979" }, 
        form_control_disabled_color : { type: String, default: "#797979" }, 
        form_control_border_color   : { type: String, default: "#797979" }, 
        primary_border_color        : { type: String, default: "#38352F" }, 
        secondary_border_color      : { type: String, default: "#FFFFFF" }, 
        dark_border_color           : { type: String, default: "#000000" }, 
        gray_border_color           : { type: String, default: "#CED4DA" }, 
        gray_dark_border_color      : { type: String, default: "#777777" }, 
        primary_svg_color           : { type: String, default: "#303030" }, 
        secondary_svg_color         : { type: String, default: "#FFA072" }, 
        tertiary_svg_color          : { type: String, default: "#FFFFFF" }, 
        starts_color                : { type: String, default: "#FFA200" }, 
        sale_tag_color              : { type: String, default: "#FF887C" }, 
        new_tag_color               : { type: String, default: "#FFA072" }, 
        primary_shadow_color        : { type: String, default: "#707070" }, 
        secondary_shadow_color      : { type: String, default: "#FFFFFF" }, 
        background_white_color      : { type: String, default: "#FFFFFF" }, 
        background_black_color      : { type: String, default: "#000000" }, 
        background_gray_color       : { type: String, default: "#F8F8F8" }
    } },
    
    created_at      : { type: Date                          , default: Date.now },
    updated_at      : { type: Date                          , default: Date.now },
    deleted_at      : { type: Date                          , default: null },
    deleted         : { type: Boolean                       , default: false },
    status          : { type: String                        , default: 'active' }
});

module.exports = mongoose.model( 'back_storefront_theme', storefrontThemeSchema );